
default: &default
  adapter: postgresql
  port: 5432
  pool: 20
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  username: rails2
  password: rails2
  host: 127.0.0.1
  database: procesod

test:
  <<: *default
  username: rails2
  password: rails2
  host: 127.0.0.1
  database: procesot

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  username: railwayapp
  password: <%= ENV["RAILWAYAPP_DATABASE_PASSWORD"] %>
  database: railwayapp_production
  
   
   